### PR TITLE
Make IAC ignore IDL4 annotation applications

### PR DESCRIPTION
**Pull request by okellogg**
PolyORB's IDL compiler IAC gets confused by IDL4 [annotations](http://okellogg.de/omg/idl4.html#p98).
This patch makes the lexer ignore annotation applications.

### CODE REVIEW

**Comment by okellogg** [comment]
Hello Thomas,
Thanks for reviewing.

> \[...\] So, I don't think you can skip it in the lexer (at least not without counting parentheses),

The procedure [Skip_Declaration](https://github.com/AdaCore/PolyORB/blob/e8f3a7640653aa97a1dcd7018a3ad5fe55608ec7/compilers/iac/lexer.adb#L1753) does something very similar so I got some [inspiration](https://github.com/AdaCore/PolyORB/pull/1/commits/0df933e21d36c741c14d318b1c1fb08593d7e9b6) from there.

> and it would probably make more sense to have the parser properly handle it.

Actually, I looked into that.
However, the IDL 4.2 standard section [7.4.15.4.2](http://okellogg.de/omg/idl4.html#p102) contains the following sentence:

> An annotation may be applied to any IDL constructs or sub-constructs.

I have not found an obvious place in the parser to capture the "may be applied to _any_ IDL constructs". Or am I overlooking something?

**Comment by quinot** [comment]
Indeed the specification is a bit vague in this respect. I guess you'll need to test for a T_At token at each place in the parser when a candidate construct is being parsed. This is similar to pragmas, that can appear in many places, so one approach you can take is to look for all places where we call P_Pragma (which are all triggered by seeing a T_Pragma token), and in each of these places add a case for T_At, calling a P_Annotation subprogram. There are actually only two places: in P_Definition, and in P_Export. That should get you started.

**Comment by okellogg** [comment]
> I guess you'll need to test for a T_At token at each place \[...\]
> That should get you started.

Many thanks for commenting.
Indeed, it got me [started](https://github.com/AdaCore/PolyORB/pull/1/commits/93153c2cd3a1ef6c4dfab4f1fb5377c02b9028d8).

**Comment by quinot** [comment]
Hello @okellogg, sorry for the lag in reviewing this. I'm now getting the change through internal testing.

**Pull request merged**
